export const projectdetails = [
  {
    id: 1,
    name: "REST Countries API",
    img: "",
    title: "REST Countries API with color theme switcher",
    description: "The  challenge was to integrate with the [REST Countries API] to pull country data and display it like in the designs.Also,Your users should be able to See all countries from the API on the homepage, Search for a country using an `input` field, Filter countries by region etc",
    year: "2023",
    liveUrl: "https://countriesrestapii.netlify.app/",
    githubUrl: "https://github.com/INIstheguyy/REST-API-countries",
  },
  {
    id: 2,
    name: " Space tourism website",
    img: "",
    title: "space-tourism-landing-page ",
    description: "The challenge was to build out this multi-page space tourism website,get it looking as close to the design as possible & enable users to view the optimal layout for each of the website's pages depending on their device's screen size",
    year: "2023",
    liveUrl: "https://dnbspacetourism.netlify.app/",
    githubUrl: "https://github.com/INIstheguyy/space-tourism-landing-page",
  },
  {
    id: 3,
    name: "Blog-post",
    img: "",
    title: "Blog-post web app",
    description: "I created a blog-post using react. The website performs ADD,DELETE & POST function using axios and stores data using a third-party DBMS.",
    year: "2024",
    liveUrl: "https://dnblogpost.netlify.app/",
    githubUrl: "https://github.com/INIstheguyy/Blog-post",
  },
  {
    id: 4,
    name: "",
    img: "",
    title: "",
    description: "",
    year: "",
    liveUrl: "",
    githubUrl: "",
  },
  {
    id: 5,
    name: "",
    img: "",
    title: "",
    description: "",
    year: "",
    liveUrl: "",
    githubUrl: "",
  },
  {
    id: 1,
    name: "",
    img: "",
    title: "",
    description: "",
    year: "",
    liveUrl: "",
    githubUrl: "",
  },
  {
    id: 1,
    name: "",
    img: "",
    title: "",
    description: "",
    year: "",
    liveUrl: "",
    githubUrl: "",
  },
  {
    id: 1,
    name: "",
    img: "",
    title: "",
    description: "",
    year: "",
    liveUrl: "",
    githubUrl: "",
  },
];
